import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchPythonApiServer } from "@/lib/server-api";
import JobHistory, { type Job } from "./JobHistory";

interface Worker { name: string; status: string; active_tasks: number }
interface Task { id: string; name: string; worker: string; state: string }
export default async function CeleryPage() {
  const [health, workers, active, reserved, scheduled, jobs] = await Promise.all([fetchPythonApiServer("/prod/celery"), fetchPythonApiServer("/prod/celery/workers"), fetchPythonApiServer("/prod/celery/tasks/active"), fetchPythonApiServer("/prod/celery/tasks/reserved"), fetchPythonApiServer("/prod/celery/tasks/scheduled"), fetchPythonApiServer("/prod/jobs")]) as [{ healthy?: boolean; error?: string }, { workers?: Worker[] }, { tasks?: Task[] }, { tasks?: Task[] }, { tasks?: Task[] }, { jobs?: Job[]; error?: string }];
  const groups = [{ name: "Active", tasks: active.tasks || [] }, { name: "Reserved", tasks: reserved.tasks || [] }, { name: "Scheduled", tasks: scheduled.tasks || [] }];
  return <div className="mx-auto max-w-7xl space-y-6 p-6"><div><h1 className="text-3xl font-bold tracking-tight">Celery jobs</h1><p className="text-muted-foreground">Live worker execution plus durable ingestion state from PostgreSQL.</p></div>{!health.healthy && <div className="border border-destructive/30 bg-destructive/10 p-4"><p className="font-medium text-destructive">No Celery worker responded</p><p className="text-xs text-muted-foreground">{health.error || "Start a worker and ensure Redis is reachable."}</p></div>}<Card><CardHeader><CardTitle>Workers</CardTitle><CardDescription>{workers.workers?.length || 0} online worker(s)</CardDescription></CardHeader><CardContent className="space-y-2">{(workers.workers || []).map((worker) => <div key={worker.name} className="flex items-center justify-between border p-3"><div><p className="font-medium">{worker.name}</p><p className="text-xs text-muted-foreground">{worker.active_tasks} active task(s)</p></div><Badge>{worker.status}</Badge></div>)}</CardContent></Card><JobHistory initialJobs={jobs.jobs || []} initialError={jobs.error} /><div className="grid gap-4 lg:grid-cols-3">{groups.map((group) => <Card key={group.name}><CardHeader><CardTitle>{group.name}</CardTitle><CardDescription>{group.tasks.length} task(s)</CardDescription></CardHeader><CardContent className="space-y-2">{group.tasks.map((task) => <div key={task.id} className="border p-3"><p className="break-all font-medium">{task.name}</p><p className="text-xs text-muted-foreground">{task.worker} · {task.state}</p></div>)}{group.tasks.length === 0 && <p className="text-muted-foreground">Nothing {group.name.toLowerCase()}.</p>}</CardContent></Card>)}</div></div>;
}
